apiVersion: v1
kind: Service
metadata:
  name: users-forum-client
  namespace: users-forum-client
spec:
  selector:
    app: users-forum-client
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP