apiVersion: v1
kind: Service
metadata:
  name: users-forum-service
  namespace: users-forum-service
spec:
  selector:
    app: users-forum-service
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
  